APP_VERSION = '1.1.0'


# Script
XUNIT_PATH_ENV_VAR = "XUNIT_PATH"
XUNIT_PATH_GLOB_ENV_VAR = "XUNIT_GLOB"
SLACK_TOKEN_ENV_VAR = "SLACK_TOKEN"
SLACK_CHANNEL_ENV_VAR = "SLACK_CHANNEL"
EXIT_ON_FAILURE_ENV_VAR = "EXIT_CODE_FROM_REPORT"
ONLY_NOTIFY_ON_ISSUES_ENV_VAR = "ONLY_NOTIFY_ON_ISSUES"

PASS_COLOR = "#3CB371"
FAIL_COLOR = "#DC143C"
